# This is a basic workflow to help you get started with Actions

name: Sync PR to GitLab

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整 Git 历史
          ref: ${{ github.event.pull_request.head.ref }}  # PR 分支
          
      - name: Add GitLab remote
        run: |
          git remote add gitlab https://${{ vars.GITLAB_USER_NAME }}:${{ secrets.GITLAB_TOKEN }}@git.qcjzai.cn/liwang/github-test.git

      - name: Push PR branch to GitLab
        run: |
          git push gitlab ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.title }}  # 推送 PR 分支
