# This is a basic workflow to help you get started with Actions

name: Sync PR to GitLab

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: GITLAB
    steps:
      - name: Debug Info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Pull Request Head Ref: ${{ github.event.pull_request.head.ref }}"
          echo "Pull Request Head Repo: ${{ github.event.pull_request.head.repo.full_name }}"
          
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0  # 获取完整 Git 历史
          ref: ${{ github.event.pull_request.head.ref }}  # PR 分支
          
      - name: Add GitLab remote
        env:
          GH_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          AS: ${{ vars.GITLAB_USER_NAME }}
        run: |
          echo "${{ vars.AS }} ${{env.AS}} ${{env.GH_TOKEN}} ${{vars.GH_TOKEN}}"
          echo " ${{ env.GITLAB }} - ${{ env.GITLAB_USER_NAME}} - ${{vars.GITLAB.GITLAB_USER_NAME}}"
          echo "${{ vars.GITLAB_USER_NAME }}:${{ secrets.GITLAB_TOKEN }}@${{ vars.GITLAB_DOMAIN }}${{ vars.GITLAB_PATH }}"
          git remote add gitlab https://${{ vars.GITLAB_USER_NAME }}:${{ secrets.GITLAB_TOKEN }}@${{ vars.GITLAB_DOMAIN }}${{ vars.GITLAB_PATH }}

      - name: Push PR branch to GitLab
        run: |
          git push gitlab ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.user.login }}_${{ github.event.pull_request.head.ref }}  # 推送 PR 分支
